<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUjgrjbt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUjgrjbt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUjgrjbt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUjgrjbt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUjgrjbt\appProdProjectContainer([
    'container.build_hash' => 'Ujgrjbt',
    'container.build_id' => 'cb2e829f',
    'container.build_time' => 1610537011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUjgrjbt');
